name: Test Python and Bash Scripts

on:
  pull_request:
    branches: [ main ]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pega os arquivos do repositório
      - uses: actions/checkout@v4

      # 2️⃣ Roda o script Python
      - name: Run Python script
        run: python3 test_1.py

      # 3️⃣ Roda o script Bash
      - name: Run Bash script
        run: |
          chmod +x test_2.sh
          # Rodando com input simulado para não travar na Action
          echo "Eliahu" | ./test_2.sh
